
# Identity Matrix Numpy

This notebook will just go through the basic topics in order:

* Identity Matrix

* Matrix Multiply with Identity Matrix

- toc: true
- badges: true
- comments: true
- categories: [python],[math skills]

### Numpy Import

In [1]:
import numpy as np

### Initialize matrix A and B

In [2]:
A = [[1, 2], [4,5]]
B = [[1,1], [0, 2]]


### Show Matrix A

In [3]:
A

[[1, 2], [4, 5]]

### Show Matrix B

In [4]:
B

[[1, 1], [0, 2]]

### Convert Matrix A from List to Numpy Array

In [5]:
A_np = np.array(A)
A_np

array([[1, 2],
       [4, 5]])

### Convert Matrix B from List to Numpy Array

In [6]:
B_np = np.array(B)
B_np

array([[1, 1],
       [0, 2]])

### Initialize a 2 by 2 identity matrix

In [7]:
I = np.eye(2)

### Show Matrix I

In [8]:
I

array([[1., 0.],
       [0., 1.]])

### What happens when we multiply I*A ?

In [13]:
IA_np = I @ A_np
IA_np

array([[1., 2.],
       [4., 5.]])

### What happens when we multiply A * I ?

In [14]:
A_npI = A_np @ I
A_npI

array([[1., 2.],
       [4., 5.]])