
# Inverse and Transpose Matrix in Numpy

This notebook will just go through the basic topics in order:

* Inverse

* Transpose

* Identity Matrix = A_inv * A

- toc: true
- badges: true
- comments: true
- categories: [ML-Math Skill]

### Numpy Import

In [1]:
import numpy as np

### Initialize Matrix A

In [2]:
A_np = np.array([[1,2,0],[0,5,6],[7,0,9]])
A_np

array([[1, 2, 0],
       [0, 5, 6],
       [7, 0, 9]])

### Transpose A

In [3]:
A_trans = A_np.transpose()
A_trans

array([[1, 0, 7],
       [2, 5, 0],
       [0, 6, 9]])

### Inverse A

In [5]:
A_inv = np.linalg.inv(A_np)
A_inv

array([[ 0.34883721, -0.13953488,  0.09302326],
       [ 0.3255814 ,  0.06976744, -0.04651163],
       [-0.27131783,  0.10852713,  0.03875969]])

### What is A^(-1)*A?

In [8]:
A_invA = np.linalg.inv(A_np) @ A_np
A_invA

array([[ 1.00000000e+00,  0.00000000e+00,  1.80411242e-16],
       [ 2.08166817e-17,  1.00000000e+00,  3.46944695e-17],
       [-3.46944695e-17,  0.00000000e+00,  1.00000000e+00]])

### Become Identity Matrix is it? can see by below

### Now what happens when we multiply A * A_invA = A itself ?

In [10]:
AI = A_np @ A_invA
AI

array([[ 1.00000000e+00,  2.00000000e+00,  2.49800181e-16],
       [-1.04083409e-16,  5.00000000e+00,  6.00000000e+00],
       [ 7.00000000e+00,  0.00000000e+00,  9.00000000e+00]])