In [1]:
import numpy as np

In [4]:
A = [[1, 2, 4], [5, 3, 2]]
B = [[1, 3, 4], [1, 1, 1]]

In [7]:
A

[[1, 2, 4], [5, 3, 2]]

In [8]:
B


[[1, 3, 4], [1, 1, 1]]

In [11]:
A_np = np.array(A)
A_np

array([[1, 2, 4],
       [5, 3, 2]])

In [12]:
B_np = np.array(B)
B_np

array([[1, 3, 4],
       [1, 1, 1]])

In [13]:
s = 2

In [14]:
add_AB = A_np + B_np
add_AB

array([[2, 5, 8],
       [6, 4, 3]])

In [16]:
sub_AB = A_np - B_np
sub_AB

array([[ 0, -1,  0],
       [ 4,  2,  1]])

In [17]:
mult_As = A_np * s
mult_As

array([[ 2,  4,  8],
       [10,  6,  4]])

In [18]:
div_As = A_np / s
div_As

array([[0.5, 1. , 2. ],
       [2.5, 1.5, 1. ]])

In [19]:
add_As = A_np + s
add_As


array([[3, 4, 6],
       [7, 5, 4]])