
# Matrix and Vector Numpy

This notebook will just go through the basic topics in order:

* Matrix

* Vector

- toc: true
- badges: true
- comments: true
- categories: [python]

### Numpy Import

In [ ]:
import numpy as np

### Initialize matrix A and B

In [34]:
A = [[1, 2, 4], [5, 3, 2]]
B = [[1, 3, 4], [1, 1, 1]]


### Show Matrix A

In [35]:
A

[[1, 2, 4], [5, 3, 2]]

### Show Matrix B

In [36]:
B

[[1, 3, 4], [1, 1, 1]]

### Convert Matrix A from List to Numpy Array

In [37]:
A_np = np.array(A)
A_np

array([[1, 2, 4],
       [5, 3, 2]])

### Convert Matrix B from List to Numpy Array

In [38]:
B_np = np.array(B)
B_np

array([[1, 3, 4],
       [1, 1, 1]])

### Initialize constant s

In [39]:
s = 2

### See how element-wise addition works

In [ ]:
add_AB = A_np + B_np
add_AB

### See how element-wise subtraction works

In [ ]:
sub_AB = A_np - B_np
sub_AB

### See how scalar multiplication works

In [ ]:
mult_As = A_np * s
mult_As

### Divide A by s

In [ ]:
div_As = A_np / s
div_As

### What happens if we have a Matrix + scalar?

In [ ]:
add_As = A_np + s
add_As

### Initialize vector v

In [ ]:
v = np.array([[1],[1],[1]])
v

### Show Matrix A again

In [49]:
A_np

array([[1, 2, 4],
       [5, 3, 2]])

### Multiply A * v

In [50]:
Av = A_np @ v
Av

array([[ 7],
       [10]])