
# Matrix and Vector Numpy

This notebook will just go through the basic topics in order:

* Matrix
   
* Vector 

- toc: true 
- badges: true
- comments: true
- categories: [python]

In [33]:
import numpy as np

In [34]:
A = [[1, 2, 4], [5, 3, 2]]
B = [[1, 3, 4], [1, 1, 1]]

In [35]:
A

[[1, 2, 4], [5, 3, 2]]

In [36]:
B


[[1, 3, 4], [1, 1, 1]]

In [37]:
A_np = np.array(A)
A_np

array([[1, 2, 4],
       [5, 3, 2]])

In [38]:
B_np = np.array(B)
B_np

array([[1, 3, 4],
       [1, 1, 1]])

In [39]:
s = 2

In [40]:
add_AB = A_np + B_np
add_AB

array([[2, 5, 8],
       [6, 4, 3]])

In [41]:
sub_AB = A_np - B_np
sub_AB

array([[ 0, -1,  0],
       [ 4,  2,  1]])

In [42]:
mult_As = A_np * s
mult_As

array([[ 2,  4,  8],
       [10,  6,  4]])

In [43]:
div_As = A_np / s
div_As

array([[0.5, 1. , 2. ],
       [2.5, 1.5, 1. ]])

In [44]:
add_As = A_np + s
add_As

array([[3, 4, 6],
       [7, 5, 4]])

In [45]:
v = np.array([[1],[1],[1]])
v


array([[1],
       [1],
       [1]])

In [46]:
Av = A_np @ v
Av

array([[ 7],
       [10]])